-- Supabase SQL-Migration: Chicken-Markt Inventar und Trades

CREATE TABLE IF NOT EXISTS public.market_inventory (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    item_key text NOT NULL,
    quantity integer NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT market_inventory_username_item_key_key UNIQUE (username, item_key)
);

CREATE TABLE IF NOT EXISTS public.market_trades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    item_key text NOT NULL,
    action text NOT NULL CHECK (action IN ('buy', 'sell')),
    quantity integer NOT NULL CHECK (quantity > 0),
    price integer NOT NULL CHECK (price > 0),
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.market_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.market_trades ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Market inventory is publicly readable" ON public.market_inventory;
DROP POLICY IF EXISTS "Anyone can create market inventory" ON public.market_inventory;
DROP POLICY IF EXISTS "Anyone can update market inventory" ON public.market_inventory;

CREATE POLICY "Market inventory is publicly readable"
ON public.market_inventory
FOR SELECT
USING (true);

CREATE POLICY "Anyone can create market inventory"
ON public.market_inventory
FOR INSERT
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND length(trim(item_key)) BETWEEN 1 AND 50
    AND quantity >= 0
);

CREATE POLICY "Anyone can update market inventory"
ON public.market_inventory
FOR UPDATE
USING (true)
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND length(trim(item_key)) BETWEEN 1 AND 50
    AND quantity >= 0
);

DROP POLICY IF EXISTS "Market trades are publicly readable" ON public.market_trades;
DROP POLICY IF EXISTS "Anyone can create market trades" ON public.market_trades;

CREATE POLICY "Market trades are publicly readable"
ON public.market_trades
FOR SELECT
USING (true);

CREATE POLICY "Anyone can create market trades"
ON public.market_trades
FOR INSERT
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND length(trim(item_key)) BETWEEN 1 AND 50
    AND action IN ('buy', 'sell')
    AND quantity > 0
    AND price > 0
);

CREATE INDEX IF NOT EXISTS market_inventory_username_idx
ON public.market_inventory (username);

CREATE INDEX IF NOT EXISTS market_trades_username_created_idx
ON public.market_trades (username, created_at DESC);

GRANT SELECT, INSERT, UPDATE ON public.market_inventory TO anon, authenticated;
GRANT SELECT, INSERT ON public.market_trades TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
