-- Supabase SQL-Migration: globales Scoreboard fuer Chicken Racer

CREATE TABLE IF NOT EXISTS public.chicken_racer_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    score integer NOT NULL CHECK (score >= 0),
    round integer NOT NULL DEFAULT 1 CHECK (round >= 1),
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.chicken_racer_scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Chicken racer scores are publicly readable" ON public.chicken_racer_scores;
DROP POLICY IF EXISTS "Anyone can submit chicken racer scores" ON public.chicken_racer_scores;

CREATE POLICY "Chicken racer scores are publicly readable"
ON public.chicken_racer_scores
FOR SELECT
USING (true);

CREATE POLICY "Anyone can submit chicken racer scores"
ON public.chicken_racer_scores
FOR INSERT
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND score >= 0
    AND round >= 1
);

CREATE INDEX IF NOT EXISTS chicken_racer_scores_score_round_created_at_idx
ON public.chicken_racer_scores (score DESC, round DESC, created_at ASC);

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT ON public.chicken_racer_scores TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
