-- Supabase SQL-Migration: Shop-Kategorien und Bestrafungsrad-Kaeufe

ALTER TABLE public.shop_items
ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT 'In Stream Rewards';

ALTER TABLE public.shop_items
DROP CONSTRAINT IF EXISTS shop_items_category_check;

ALTER TABLE public.shop_items
ADD CONSTRAINT shop_items_category_check
CHECK (category IN ('In Stream Rewards', 'Bestrafungs Ideen', 'Idee Bestrafungsrad', 'Aufgaben', 'Aufgaben Ideen', 'Idee Aufgabenrad', 'Out of Stream Rewards'));

UPDATE public.shop_items
SET category = 'Bestrafungs Ideen'
WHERE category = 'Idee Bestrafungsrad';

UPDATE public.shop_items
SET category = 'Out of Stream Rewards'
WHERE name = '🎮 Steam Random Key';

CREATE TABLE IF NOT EXISTS public.purchases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    reward_name text NOT NULL,
    price integer NOT NULL CHECK (price >= 0),
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.purchases
ADD COLUMN IF NOT EXISTS reward_category text NOT NULL DEFAULT 'In Stream Rewards';

ALTER TABLE public.purchases
ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'open';

ALTER TABLE public.purchases
ADD COLUMN IF NOT EXISTS resolved_at timestamptz;

ALTER TABLE public.purchases
DROP CONSTRAINT IF EXISTS purchases_reward_category_check;

ALTER TABLE public.purchases
ADD CONSTRAINT purchases_reward_category_check
CHECK (reward_category IN ('In Stream Rewards', 'Bestrafungs Ideen', 'Idee Bestrafungsrad', 'Aufgaben', 'Aufgaben Ideen', 'Idee Aufgabenrad', 'Out of Stream Rewards'));

UPDATE public.purchases
SET reward_category = 'Bestrafungs Ideen'
WHERE reward_category = 'Idee Bestrafungsrad';

ALTER TABLE public.purchases
DROP CONSTRAINT IF EXISTS purchases_status_check;

ALTER TABLE public.purchases
ADD CONSTRAINT purchases_status_check
CHECK (status IN ('open', 'done'));

ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Purchases are publicly readable" ON public.purchases;
DROP POLICY IF EXISTS "Anyone can create purchases" ON public.purchases;
DROP POLICY IF EXISTS "Anyone can update purchases" ON public.purchases;

CREATE POLICY "Purchases are publicly readable"
ON public.purchases
FOR SELECT
USING (true);

CREATE POLICY "Anyone can create purchases"
ON public.purchases
FOR INSERT
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND length(trim(reward_name)) BETWEEN 1 AND 100
    AND price >= 0
);

CREATE POLICY "Anyone can update purchases"
ON public.purchases
FOR UPDATE
USING (true)
WITH CHECK (
    status IN ('open', 'done')
);

CREATE INDEX IF NOT EXISTS purchases_category_status_created_idx
ON public.purchases (reward_category, status, created_at ASC);

GRANT SELECT, INSERT, UPDATE ON public.purchases TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
