-- Supabase SQL-Migration: News im Zeitungsstil

CREATE TABLE IF NOT EXISTS public.news_posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    body text NOT NULL,
    image_url text,
    active boolean NOT NULL DEFAULT true,
    published_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.news_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "News posts are publicly readable" ON public.news_posts;
DROP POLICY IF EXISTS "Anyone can create news posts" ON public.news_posts;
DROP POLICY IF EXISTS "Anyone can update news posts" ON public.news_posts;

CREATE POLICY "News posts are publicly readable"
ON public.news_posts
FOR SELECT
USING (true);

CREATE POLICY "Anyone can create news posts"
ON public.news_posts
FOR INSERT
WITH CHECK (
    length(trim(title)) BETWEEN 1 AND 140
    AND length(trim(body)) BETWEEN 1 AND 2500
);

CREATE POLICY "Anyone can update news posts"
ON public.news_posts
FOR UPDATE
USING (true)
WITH CHECK (
    length(trim(title)) BETWEEN 1 AND 140
    AND length(trim(body)) BETWEEN 1 AND 2500
);

CREATE INDEX IF NOT EXISTS news_posts_active_published_idx
ON public.news_posts (active, published_at DESC);

GRANT SELECT, INSERT, UPDATE ON public.news_posts TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
