-- Supabase SQL-Migration: Dungeons-and-Dragons-Lobbys

CREATE TABLE IF NOT EXISTS public.dnd_lobbies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL DEFAULT '',
    owner text NOT NULL,
    is_private boolean NOT NULL DEFAULT false,
    password_hash text NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dnd_players (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lobby_id bigint NOT NULL REFERENCES public.dnd_lobbies(id) ON DELETE CASCADE,
    username text NOT NULL,
    character_name text NOT NULL,
    character_class text NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT dnd_players_lobby_username_key UNIQUE (lobby_id, username)
);

CREATE TABLE IF NOT EXISTS public.dnd_rolls (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lobby_id bigint NOT NULL REFERENCES public.dnd_lobbies(id) ON DELETE CASCADE,
    username text NOT NULL,
    character_name text NOT NULL,
    notation text NOT NULL,
    reason text NOT NULL DEFAULT '',
    rolls text NOT NULL,
    total integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.dnd_lobbies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dnd_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dnd_rolls ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "DND lobbies are publicly readable" ON public.dnd_lobbies;
DROP POLICY IF EXISTS "Anyone can create DND lobbies" ON public.dnd_lobbies;
DROP POLICY IF EXISTS "Anyone can update DND lobbies" ON public.dnd_lobbies;
DROP POLICY IF EXISTS "DND players are publicly readable" ON public.dnd_players;
DROP POLICY IF EXISTS "Anyone can join DND lobbies" ON public.dnd_players;
DROP POLICY IF EXISTS "Anyone can update DND players" ON public.dnd_players;
DROP POLICY IF EXISTS "DND rolls are publicly readable" ON public.dnd_rolls;
DROP POLICY IF EXISTS "Anyone can create DND rolls" ON public.dnd_rolls;

CREATE POLICY "DND lobbies are publicly readable"
ON public.dnd_lobbies
FOR SELECT
USING (true);

CREATE POLICY "Anyone can create DND lobbies"
ON public.dnd_lobbies
FOR INSERT
WITH CHECK (
    length(trim(name)) BETWEEN 1 AND 80
    AND length(trim(owner)) BETWEEN 1 AND 50
);

CREATE POLICY "Anyone can update DND lobbies"
ON public.dnd_lobbies
FOR UPDATE
USING (true)
WITH CHECK (length(trim(name)) BETWEEN 1 AND 80);

CREATE POLICY "DND players are publicly readable"
ON public.dnd_players
FOR SELECT
USING (true);

CREATE POLICY "Anyone can join DND lobbies"
ON public.dnd_players
FOR INSERT
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND length(trim(character_name)) BETWEEN 1 AND 80
    AND length(trim(character_class)) BETWEEN 1 AND 40
);

CREATE POLICY "Anyone can update DND players"
ON public.dnd_players
FOR UPDATE
USING (true)
WITH CHECK (length(trim(username)) BETWEEN 1 AND 50);

CREATE POLICY "DND rolls are publicly readable"
ON public.dnd_rolls
FOR SELECT
USING (true);

CREATE POLICY "Anyone can create DND rolls"
ON public.dnd_rolls
FOR INSERT
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND length(trim(notation)) BETWEEN 1 AND 40
    AND total BETWEEN -10000 AND 10000
);

CREATE INDEX IF NOT EXISTS dnd_lobbies_active_created_idx
ON public.dnd_lobbies (active, created_at DESC);

CREATE INDEX IF NOT EXISTS dnd_players_lobby_active_idx
ON public.dnd_players (lobby_id, active, created_at ASC);

CREATE INDEX IF NOT EXISTS dnd_rolls_lobby_created_idx
ON public.dnd_rolls (lobby_id, created_at DESC);

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.dnd_lobbies TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.dnd_players TO anon, authenticated;
GRANT SELECT, INSERT ON public.dnd_rolls TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
