-- Supabase SQL-Migration: globales Scoreboard fuer Chicken Jump

CREATE TABLE IF NOT EXISTS public.chicken_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    score integer NOT NULL CHECK (score >= 0),
    level integer NOT NULL DEFAULT 1 CHECK (level >= 1),
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.chicken_scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Chicken scores are publicly readable" ON public.chicken_scores;
DROP POLICY IF EXISTS "Anyone can submit chicken scores" ON public.chicken_scores;

CREATE POLICY "Chicken scores are publicly readable"
ON public.chicken_scores
FOR SELECT
USING (true);

CREATE POLICY "Anyone can submit chicken scores"
ON public.chicken_scores
FOR INSERT
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND score >= 0
    AND level >= 1
);

CREATE INDEX IF NOT EXISTS chicken_scores_score_created_at_idx
ON public.chicken_scores (score DESC, created_at ASC);

GRANT SELECT, INSERT ON public.chicken_scores TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
