-- Supabase SQL-Migration: Chicken-Handel zwischen Mitgliedern

CREATE TABLE IF NOT EXISTS public.chicken_trades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester text NOT NULL,
    recipient text NOT NULL,
    trade_type text NOT NULL CHECK (trade_type IN ('gift', 'request')),
    amount integer NOT NULL CHECK (amount > 0),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
    created_at timestamptz NOT NULL DEFAULT now(),
    responded_at timestamptz
);

ALTER TABLE public.chicken_trades ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Chicken trades are readable" ON public.chicken_trades;
DROP POLICY IF EXISTS "Anyone can create chicken trades" ON public.chicken_trades;
DROP POLICY IF EXISTS "Anyone can update chicken trades" ON public.chicken_trades;

CREATE POLICY "Chicken trades are readable"
ON public.chicken_trades
FOR SELECT
USING (true);

CREATE POLICY "Anyone can create chicken trades"
ON public.chicken_trades
FOR INSERT
WITH CHECK (
    length(trim(requester)) BETWEEN 1 AND 50
    AND length(trim(recipient)) BETWEEN 1 AND 50
    AND requester <> recipient
    AND amount > 0
    AND trade_type IN ('gift', 'request')
    AND status = 'pending'
);

CREATE POLICY "Anyone can update chicken trades"
ON public.chicken_trades
FOR UPDATE
USING (true)
WITH CHECK (status IN ('pending', 'accepted', 'rejected'));

CREATE INDEX IF NOT EXISTS chicken_trades_recipient_status_idx
ON public.chicken_trades (recipient, status, created_at DESC);

CREATE INDEX IF NOT EXISTS chicken_trades_requester_status_idx
ON public.chicken_trades (requester, status, created_at DESC);

GRANT SELECT, INSERT, UPDATE ON public.chicken_trades TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
