-- Supabase SQL-Migration: globales Scoreboard fuer Braincell Survivor

CREATE TABLE IF NOT EXISTS public.braincell_survivor_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    score integer NOT NULL CHECK (score >= 0),
    seconds_survived integer NOT NULL DEFAULT 0 CHECK (seconds_survived >= 0),
    level integer NOT NULL DEFAULT 1 CHECK (level >= 1),
    kills integer NOT NULL DEFAULT 0 CHECK (kills >= 0),
    build text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.braincell_survivor_scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Braincell survivor scores are publicly readable" ON public.braincell_survivor_scores;
DROP POLICY IF EXISTS "Anyone can submit braincell survivor scores" ON public.braincell_survivor_scores;

CREATE POLICY "Braincell survivor scores are publicly readable"
ON public.braincell_survivor_scores
FOR SELECT
USING (true);

CREATE POLICY "Anyone can submit braincell survivor scores"
ON public.braincell_survivor_scores
FOR INSERT
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND score >= 0
    AND seconds_survived >= 0
    AND level >= 1
    AND kills >= 0
);

CREATE INDEX IF NOT EXISTS braincell_survivor_scores_score_time_created_at_idx
ON public.braincell_survivor_scores (score DESC, seconds_survived DESC, created_at ASC);

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT ON public.braincell_survivor_scores TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
