-- Supabase SQL-Migration: Daily Rewards fuer wiederkehrende Viewer

CREATE TABLE IF NOT EXISTS public.daily_rewards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    reward_date date NOT NULL,
    chickens integer NOT NULL DEFAULT 0 CHECK (chickens >= 0),
    braincells integer NOT NULL DEFAULT 0 CHECK (braincells >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT daily_rewards_username_reward_date_key UNIQUE (username, reward_date)
);

ALTER TABLE public.daily_rewards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Daily rewards are publicly readable" ON public.daily_rewards;
DROP POLICY IF EXISTS "Anyone can claim daily rewards" ON public.daily_rewards;

CREATE POLICY "Daily rewards are publicly readable"
ON public.daily_rewards
FOR SELECT
USING (true);

CREATE POLICY "Anyone can claim daily rewards"
ON public.daily_rewards
FOR INSERT
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND chickens >= 0
    AND braincells >= 0
);

CREATE INDEX IF NOT EXISTS daily_rewards_username_reward_date_idx
ON public.daily_rewards (username, reward_date DESC);

GRANT SELECT, INSERT ON public.daily_rewards TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
