-- Supabase SQL-Migration: Bearbeitbare Patch Notes

CREATE TABLE IF NOT EXISTS public.patch_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version text NOT NULL,
    title text NOT NULL,
    changes text NOT NULL,
    active boolean NOT NULL DEFAULT true,
    published_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.patch_notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Patch notes are publicly readable" ON public.patch_notes;
DROP POLICY IF EXISTS "Anyone can create patch notes" ON public.patch_notes;
DROP POLICY IF EXISTS "Anyone can update patch notes" ON public.patch_notes;

CREATE POLICY "Patch notes are publicly readable"
ON public.patch_notes
FOR SELECT
USING (true);

CREATE POLICY "Anyone can create patch notes"
ON public.patch_notes
FOR INSERT
WITH CHECK (
    length(trim(version)) BETWEEN 1 AND 80
    AND length(trim(title)) BETWEEN 1 AND 160
    AND length(trim(changes)) BETWEEN 1 AND 4000
);

CREATE POLICY "Anyone can update patch notes"
ON public.patch_notes
FOR UPDATE
USING (true)
WITH CHECK (
    length(trim(version)) BETWEEN 1 AND 80
    AND length(trim(title)) BETWEEN 1 AND 160
    AND length(trim(changes)) BETWEEN 1 AND 4000
);

CREATE INDEX IF NOT EXISTS patch_notes_active_published_idx
ON public.patch_notes (active, published_at DESC);

GRANT SELECT, INSERT, UPDATE ON public.patch_notes TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
