-- Supabase SQL-Migration: verwaltbare Shop-Items mit Chicken-Preisen

CREATE TABLE IF NOT EXISTS public.shop_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text,
    price integer NOT NULL CHECK (price > 0),
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.shop_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Shop items are publicly readable" ON public.shop_items;
DROP POLICY IF EXISTS "Anyone can create shop items" ON public.shop_items;
DROP POLICY IF EXISTS "Anyone can update shop items" ON public.shop_items;

CREATE POLICY "Shop items are publicly readable"
ON public.shop_items
FOR SELECT
USING (true);

CREATE POLICY "Anyone can create shop items"
ON public.shop_items
FOR INSERT
WITH CHECK (
    length(trim(name)) BETWEEN 1 AND 100
    AND price > 0
);

CREATE POLICY "Anyone can update shop items"
ON public.shop_items
FOR UPDATE
USING (true)
WITH CHECK (price > 0);

CREATE INDEX IF NOT EXISTS shop_items_active_price_idx
ON public.shop_items (active, price ASC);

INSERT INTO public.shop_items (name, description, price, active)
SELECT '⭐ 1 Woche VIP', 'VIP für 1 Woche', 10000, true
WHERE NOT EXISTS (
    SELECT 1 FROM public.shop_items WHERE name = '⭐ 1 Woche VIP'
);

INSERT INTO public.shop_items (name, description, price, active)
SELECT '🎮 Steam Random Key', 'Zufälliger Steam Key', 50000, true
WHERE NOT EXISTS (
    SELECT 1 FROM public.shop_items WHERE name = '🎮 Steam Random Key'
);

INSERT INTO public.shop_items (name, description, price, active)
SELECT '💬 Discord Frage', 'Frage im Discord stellen', 5000, true
WHERE NOT EXISTS (
    SELECT 1 FROM public.shop_items WHERE name = '💬 Discord Frage'
);

INSERT INTO public.shop_items (name, description, price, active)
SELECT '🖼️ Zuschauerbild neben Facecam', 'Bild neben der Facecam', 2500, true
WHERE NOT EXISTS (
    SELECT 1 FROM public.shop_items WHERE name = '🖼️ Zuschauerbild neben Facecam'
);

GRANT SELECT, INSERT, UPDATE ON public.shop_items TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
