-- Supabase SQL-Migration: globales Scoreboard fuer Chicken Snake

CREATE TABLE IF NOT EXISTS public.chicken_snake_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    score integer NOT NULL CHECK (score >= 0),
    length integer NOT NULL DEFAULT 3 CHECK (length >= 1),
    combo integer NOT NULL DEFAULT 1 CHECK (combo >= 1),
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.chicken_snake_scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Chicken snake scores are publicly readable" ON public.chicken_snake_scores;
DROP POLICY IF EXISTS "Anyone can submit chicken snake scores" ON public.chicken_snake_scores;

CREATE POLICY "Chicken snake scores are publicly readable"
ON public.chicken_snake_scores
FOR SELECT
USING (true);

CREATE POLICY "Anyone can submit chicken snake scores"
ON public.chicken_snake_scores
FOR INSERT
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND score >= 0
    AND length >= 1
    AND combo >= 1
);

CREATE INDEX IF NOT EXISTS chicken_snake_scores_score_length_combo_created_at_idx
ON public.chicken_snake_scores (score DESC, length DESC, combo DESC, created_at ASC);

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT ON public.chicken_snake_scores TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
