-- Supabase SQL-Migration: Dungeons-and-Dragons-Lobbys

CREATE TABLE IF NOT EXISTS public.dnd_lobbies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL DEFAULT '',
    owner text NOT NULL,
    is_private boolean NOT NULL DEFAULT false,
    password_hash text NOT NULL DEFAULT '',
    scene text NOT NULL DEFAULT '',
    quest_log text NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dnd_players (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lobby_id bigint NOT NULL REFERENCES public.dnd_lobbies(id) ON DELETE CASCADE,
    username text NOT NULL,
    character_name text NOT NULL,
    character_class text NOT NULL,
    race text NOT NULL DEFAULT 'Mensch',
    level integer NOT NULL DEFAULT 1 CHECK (level BETWEEN 1 AND 20),
    max_hp integer NOT NULL DEFAULT 10 CHECK (max_hp BETWEEN 1 AND 999),
    current_hp integer NOT NULL DEFAULT 10 CHECK (current_hp BETWEEN 0 AND 999),
    armor_class integer NOT NULL DEFAULT 10 CHECK (armor_class BETWEEN 1 AND 40),
    initiative integer NOT NULL DEFAULT 0 CHECK (initiative BETWEEN -20 AND 30),
    strength integer NOT NULL DEFAULT 10 CHECK (strength BETWEEN 1 AND 30),
    dexterity integer NOT NULL DEFAULT 10 CHECK (dexterity BETWEEN 1 AND 30),
    constitution integer NOT NULL DEFAULT 10 CHECK (constitution BETWEEN 1 AND 30),
    intelligence integer NOT NULL DEFAULT 10 CHECK (intelligence BETWEEN 1 AND 30),
    wisdom integer NOT NULL DEFAULT 10 CHECK (wisdom BETWEEN 1 AND 30),
    charisma integer NOT NULL DEFAULT 10 CHECK (charisma BETWEEN 1 AND 30),
    inventory text NOT NULL DEFAULT '',
    spells text NOT NULL DEFAULT '',
    notes text NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT dnd_players_lobby_username_key UNIQUE (lobby_id, username)
);

ALTER TABLE public.dnd_lobbies
ADD COLUMN IF NOT EXISTS scene text NOT NULL DEFAULT '';

ALTER TABLE public.dnd_lobbies
ADD COLUMN IF NOT EXISTS quest_log text NOT NULL DEFAULT '';

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS race text NOT NULL DEFAULT 'Mensch';

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS level integer NOT NULL DEFAULT 1;

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS max_hp integer NOT NULL DEFAULT 10;

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS current_hp integer NOT NULL DEFAULT 10;

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS armor_class integer NOT NULL DEFAULT 10;

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS initiative integer NOT NULL DEFAULT 0;

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS strength integer NOT NULL DEFAULT 10;

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS dexterity integer NOT NULL DEFAULT 10;

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS constitution integer NOT NULL DEFAULT 10;

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS intelligence integer NOT NULL DEFAULT 10;

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS wisdom integer NOT NULL DEFAULT 10;

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS charisma integer NOT NULL DEFAULT 10;

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS inventory text NOT NULL DEFAULT '';

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS spells text NOT NULL DEFAULT '';

ALTER TABLE public.dnd_players
ADD COLUMN IF NOT EXISTS notes text NOT NULL DEFAULT '';

ALTER TABLE public.dnd_players
DROP CONSTRAINT IF EXISTS dnd_players_stats_check;

ALTER TABLE public.dnd_players
ADD CONSTRAINT dnd_players_stats_check
CHECK (
    level BETWEEN 1 AND 20
    AND max_hp BETWEEN 1 AND 999
    AND current_hp BETWEEN 0 AND 999
    AND armor_class BETWEEN 1 AND 40
    AND initiative BETWEEN -20 AND 30
    AND strength BETWEEN 1 AND 30
    AND dexterity BETWEEN 1 AND 30
    AND constitution BETWEEN 1 AND 30
    AND intelligence BETWEEN 1 AND 30
    AND wisdom BETWEEN 1 AND 30
    AND charisma BETWEEN 1 AND 30
);

CREATE TABLE IF NOT EXISTS public.dnd_rolls (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lobby_id bigint NOT NULL REFERENCES public.dnd_lobbies(id) ON DELETE CASCADE,
    username text NOT NULL,
    character_name text NOT NULL,
    notation text NOT NULL,
    reason text NOT NULL DEFAULT '',
    rolls text NOT NULL,
    total integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.dnd_lobbies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dnd_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dnd_rolls ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "DND lobbies are publicly readable" ON public.dnd_lobbies;
DROP POLICY IF EXISTS "Anyone can create DND lobbies" ON public.dnd_lobbies;
DROP POLICY IF EXISTS "Anyone can update DND lobbies" ON public.dnd_lobbies;
DROP POLICY IF EXISTS "DND players are publicly readable" ON public.dnd_players;
DROP POLICY IF EXISTS "Anyone can join DND lobbies" ON public.dnd_players;
DROP POLICY IF EXISTS "Anyone can update DND players" ON public.dnd_players;
DROP POLICY IF EXISTS "DND rolls are publicly readable" ON public.dnd_rolls;
DROP POLICY IF EXISTS "Anyone can create DND rolls" ON public.dnd_rolls;

CREATE POLICY "DND lobbies are publicly readable"
ON public.dnd_lobbies
FOR SELECT
USING (true);

CREATE POLICY "Anyone can create DND lobbies"
ON public.dnd_lobbies
FOR INSERT
WITH CHECK (
    length(trim(name)) BETWEEN 1 AND 80
    AND length(trim(owner)) BETWEEN 1 AND 50
);

CREATE POLICY "Anyone can update DND lobbies"
ON public.dnd_lobbies
FOR UPDATE
USING (true)
WITH CHECK (length(trim(name)) BETWEEN 1 AND 80);

CREATE POLICY "DND players are publicly readable"
ON public.dnd_players
FOR SELECT
USING (true);

CREATE POLICY "Anyone can join DND lobbies"
ON public.dnd_players
FOR INSERT
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND length(trim(character_name)) BETWEEN 1 AND 80
    AND length(trim(character_class)) BETWEEN 1 AND 40
);

CREATE POLICY "Anyone can update DND players"
ON public.dnd_players
FOR UPDATE
USING (true)
WITH CHECK (length(trim(username)) BETWEEN 1 AND 50);

CREATE POLICY "DND rolls are publicly readable"
ON public.dnd_rolls
FOR SELECT
USING (true);

CREATE POLICY "Anyone can create DND rolls"
ON public.dnd_rolls
FOR INSERT
WITH CHECK (
    length(trim(username)) BETWEEN 1 AND 50
    AND length(trim(notation)) BETWEEN 1 AND 40
    AND total BETWEEN -10000 AND 10000
);

CREATE INDEX IF NOT EXISTS dnd_lobbies_active_created_idx
ON public.dnd_lobbies (active, created_at DESC);

CREATE INDEX IF NOT EXISTS dnd_players_lobby_active_idx
ON public.dnd_players (lobby_id, active, created_at ASC);

CREATE INDEX IF NOT EXISTS dnd_rolls_lobby_created_idx
ON public.dnd_rolls (lobby_id, created_at DESC);

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.dnd_lobbies TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.dnd_players TO anon, authenticated;
GRANT SELECT, INSERT ON public.dnd_rolls TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
